export const ibanData = [
  {name: 'Albania', regex: /^AL\d{2}\d{8}[A-Z0-9]{16}$/},
  {name: 'Algeria', regex: /^DZ\d{22}$/},
  {name: 'Andorra', regex: /^AD\d{10}[A-Z0-9]{12}$/},
  {name: 'Angola', regex: /^AO\d{23}$/},
  {name: 'Austria', regex: /^AT\d{18}$/},
  {name: 'Azerbaijan', regex: /^AZ\d{2}[A-Z]{4}[A-Z0-9]{20}$/},
  {name: 'Bahrain', regex: /^BH\d{2}[A-Z]{4}[A-Z0-9]{14}$/},
  {name: 'Belgium', regex: /^BE\d{2}\d{12}$/},
  {name: 'Bosnia and Herzegovina', regex: /^BA\d{2}\d{16}$/},
  {name: 'Brazil', regex: /^BR\d{25}[A-Z]{1}[A-Z0-9]{1}$/},
  {name: 'Bulgaria', regex: /^BG\d{2}[A-Z]{4}\d{4}\d{4}\d{2}$/},
  {name: 'Croatia', regex: /^HR\d{2}\d{7}\d{10}$/},
  {name: 'Cyprus', regex: /^CY\d{2}\d{8}[A-Z0-9]{16}$/},
  {name: 'Czech Republic', regex: /^CZ\d{22}$/},
  {name: 'Denmark', regex: /^DK\d{2}\d{14}$/},
  {name: 'Egypt', regex: /^EG\d{27}$/},
  {name: 'Spain', regex: /^ES\d{2}\d{4}\d{4}\d{1}\d{1}\d{10}$/},
  {name: 'Finland', regex: /^FI\d{2}\d{6}\d{7}\d{1}$/},
  {name: 'France', regex: /^FR\d{2}\d{5}\d{5}[A-Z0-9]{11}\d{2}$/},
  {name: 'United Kingdom', regex: /^GB\d{2}[A-Z]{4}\d{6}\d{8}$/},
  {name: 'Greece', regex: /^GR\d{2}\d{3}\d{4}[A-Z0-9]{16}$/},
  {name: 'Croatia', regex: /^HR\d{2}\d{7}\d{10}$/},
  {name: 'Hungary', regex: /^HU\d{2}\d{3}\d{4}\d{1}\d{15}\d{1}$/},
  {name: 'Ireland', regex: /^IE\d{2}[A-Z]{4}\d{6}\d{8}$/},
  {name: 'Italy', regex: /^IT\d{2}[A-Z]\d{5}\d{5}[A-Z0-9]{12}$/},
  {name: 'Lithuania', regex: /^LT\d{2}\d{5}\d{11}$/},
  {name: 'Luxembourg', regex: /^LU\d{2}\d{3}\d{13}$/},
  {name: 'Latvia', regex: /^LV\d{2}[A-Z]{4}[A-Z0-9]{13}$/},
  {name: 'Malta', regex: /^MT\d{2}[A-Z]{4}\d{5}[A-Z0-9]{18}$/},
  {name: 'Netherlands', regex: /^NL\d{2}[A-Z]{4}\d{10}$/},
  {name: 'Poland', regex: /^PL\d{2}\d{8}\d{16}$/},
  {name: 'Portugal', regex: /^PT\d{2}\d{4}\d{4}\d{11}\d{2}$/},
  {name: 'Romania', regex: /^RO\d{2}[A-Z]{4}[A-Z0-9]{16}$/},
  {name: 'Sweden', regex: /^SE\d{2}\d{3}\d{16}\d{1}$/},
  {name: 'Slovenia', regex: /^SI\d{2}\d{5}\d{8}\d{2}$/},
  {name: 'Slovakia', regex: /^SK\d{2}\d{4}\d{6}\d{10}$/},
];
